services:
  scim-client:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: scim-client
    ports:
      - "8001:80"
    environment:
      - SCIM_ENDPOINT=${SCIM_ENDPOINT:-https://localhost:7001/scim/v2}
      - SCIM_API_KEY=${SCIM_API_KEY:-}
      - CORS_PROXY_PORT=8002
    volumes:
      # Mount test results for external access
      - ./test-results:/usr/share/nginx/html/test-results
      - ./playwright-report:/usr/share/nginx/html/playwright-report
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - scim-network

networks:
  scim-network:
    driver: bridge 