version: '3.8'

services:
  scim-client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scim-client
    ports:
      - "8001:8001"
    environment:
      - SCIM_ENDPOINT=${SCIM_ENDPOINT:-https://localhost:7001/scim/v2}
      - SCIM_API_KEY=${SCIM_API_KEY:-}
    volumes:
      # Mount for development - allows live code changes
      - .:/app
      # Exclude node_modules from volume mount to use container's version
      - /app/node_modules
      # Mount test results for external access
      - ./test-results:/app/test-results
      - ./playwright-report:/app/playwright-report
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - scim-network

  # Optional: CORS proxy service for development
  cors-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scim-cors-proxy
    ports:
      - "8002:8002"
    command: ["python3", "simple-cors-proxy.py"]
    environment:
      - CORS_PROXY_PORT=8002
    volumes:
      - .:/app
    restart: unless-stopped
    networks:
      - scim-network

networks:
  scim-network:
    driver: bridge 